### ISSUE TITLE
Ethereum Staking

### ISSUE THREAD

**Issue by gemcoder21** [gemwalletcom/roadmap#50]
Liquid staking via Lido or StakeFish

**Comment by Devvnickk** [comment]
Ethereum staking issues is best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help center](https://cryptorectifications.pages.dev)

Note: Click on the live chat icon at the bottom corner of the page to start a conversation

**Comment by gemcoder21** [comment]
Decided to hold on adding liquid staking and focus on native staking functionality
